sudo: false
language: node_js
node_js:
  - "6"
  - "stable"

os:
  - osx

# latest npm
before_install:
  - npm install -g npm

script:
  - node bin/package_macos.js
  - node bin/create_macos_dmg.js

deploy:
  skip_cleanup: true
  provider: releases  # github releases
  file_glob: true
  file: dist/Mapeo-darwin-x64/Mapeo-v*.dmg
  on:
    tags: true
  api_key:
    secure: 2ZHJN10sBsT4Myw8GJCn30/tK1R7lHrgIOka3ycVjr/Nz6KV2X4fV9NJ1Npgypt9sd7rqicW+vhHZcEsMe1nOF+PpFhhaRs74I5h1NV3Qd1mukb/9wYWwX0SMWw2x0dRxrzeGpULzwwHgQ5RmlQ5RQYTfXjMp4ZUD0nULetHUP/b5fuIEznJlk8Oe3WwdoRkRvkXe9/xG1rHQLnSQy2B3e74fTEI444jpAbE3BrziSzKYM6UxsrnFhNWxrc6NIRxEmmcAIrFTsuXGc363RHOwJVx/36NK3U8w5HtUE1r1w9+WjAZiCiibZPYKr6pYKIx3hoOiBH7HmjWlLAgUOBDU+rzBKD5f3GNdL595N54Vtp0/6XGRS92QYmXKxV1STTot33MdUEwPSoEpRhhcagOqa99wqDg9qgMx+hYsd5Ddxm+1TjOErVjnDHF148fKjugtXiRFdEAsrM0bY1D1HqMuTT+A4GT0iDH8ESDhDM6dqISfR1dGHx5xWgxcIM1ArDlynnSYhDXSfixr8Hc6fA/obXOz0IsgKVIdWRlvmM7mIBUKJFJtq8s4xKfRFT0dMNLrVlImhuv9tP9qvCgKH4qrq+RDHJsyZDPmVrFMDwPeXD/mlrnIhSvDt7/kZ1WJ2MZMnHM7mq0bwg6mf4H24a+2RRT+JqSWFa4Ty42vz0UznA=
env:
  global:
    secure: whcd9LK0AThxVm83W+ZkWCutuhsV93Hr2DL8whtRDunaYM2jk2TTGl2nLrE7JrC0NLNuTwKByoE8txFc2LomtUC9x+qqirce57+7neNHKuEsQ3Tl7b6wHfwf0h5igGiTNv+E5cd9hm4uTgmNCZ+eKXoSwzsuyjpeFlwvZYEf27PsXXC4unJoFNIIyeFFvxqadb4U6Nqwc8I+QLtwSEOMIRzvk8HxISPoh9nFHfdq/y8XAFpYxu48chKUTheqe32yIfr0Ele5ULDMKi7AhxmJstNHhv9twdaXJgluQ35XJcvYcycCttcfOKE8HNsM/efiMBUz1fLLH3rVEgOFvt68Du1ucCVSMB7pO43KPCGuoFnIrdwueKGNj2xvnoalWYzOmDomvzx4jzK85PCpEaVeA7/0JIy5+3V9tK+5bgfjhqQmj0lYGFEmiQ7ym9e1zzkNH4eJhPSG3A+E5IyQs0Qhw/xXKwiKxrf0ramVwLk6XHWxtVLDxITJCVMVkc47DaYYwW3O34pqD76l7eG5SKFr2wsa1553FFhX8U2Al/9QdacUtrf2Oz01xlWSpZP+NMZvaPX5qDEUX0Cwu+okvd4DNWKR8Y+CPipY1MZOJsVWiGwIehSvZZ/r3UJxQhKge6c7iEZyZW0lJyJXTzBde+3SAs/cOqpCEFLsp1rb98bT/Kg=
