name: Node CD

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: npm install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Build frontend
        run: |
          npm run build
        env:
          CI: true
      - name: Publish
        run: |
          npm run dist
        env:
          CI: true
          GITHUB_CI_REF: ${{ github.ref }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
      - name: Update website release
        if: contains(github.ref, '/tags/')
        run: bin/release_latest.js
        env:
          GITHUB_TOKEN: ${{ secrets.WEBSITE_GH_TOKEN }}
      - name: Cleanup artifacts
        run: |
          npx rimraf@2 'dist/!(*.exe|*.deb|*.AppImage|*.dmg)'
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: dist
